### ISSUE TITLE
Fatal(Crash) 에러가 발생시 UrQA 서버로의 전송이 실패하는 경우가 많습니다.

### ISSUE THREAD

**Issue by easy20** [UrQA/UrQA-Client-Android#17]
오류발생시 UrQA 서버로 전송되지 못하는 경우가 많습니다.
개발자가 인위적으로 전송하는 오류는 UrQA 서버로 전송됩니다만, 의도치 않은
Fatal(Crash) 에러가 발생시 UrQA 서버로의 전송이 실패하는 경우가 많습니다.
왜냐하면 App 에서 Crash 발생시, UrQA 서버로 에러데이터가 전송되기 전에
Android Framework 에서 App 을 강제종료 시키는 경우가 발생합니다.

App 이 강제종료되기전에, 에러로그가 전송되도록 수정 부탁드립니다.

**Comment by EastComplete** [comment]
이형태로 진행을 하려고 했으니ㅏ, 인위적으로 앱 자체가 행되는 문제가 있어서, 원복하기로 했습니다.
