### ISSUE TITLE
처음 앱에 부착하여 사용중입니다. 다만 크래쉬되었을때 전송이 안되는 것 같습니다.

### ISSUE THREAD

**Issue by JeongJiMun** [UrQA/UrQA-Client-Android#21]
어제 퇴근전에 앱에 부착하여 동작하는것을 확인하고
오늘 에러를 만들어 다시 확인해보니 크래쉬정보가 웹에서 확인이 안되고있습니다.
예제코드로 새로 프로젝트를 생성해도 이런 증상이 있는데
제가 실수를 한건지는 모르겠지만,
설치법과 설명을 반복하여 읽고 셋팅해보아도 계속 이런 현상이 발생하는걸로 보아
설정문제는 아닌것 같습니다.
확인부탁드립니다.

11-04 10:41:24.867: I/UrQA(2794): UrQA Response Code : 200
11-04 10:41:25.658: I/UrQA(2794): UrQA Response Code :: 200
11-04 10:41:27.359: I/Process(2794): Sending signal. PID: 2794 SIG: 9

**Comment by EastComplete** [comment]
worker 의 문제로 인해 rabbitmq에 데이터가 보관되엇던 이슈입니다.  정상화 되었습니다.
