### ISSUE TITLE
SocketTimeoutException

### ISSUE THREAD

**Issue by EffectiveLife** [UrQA/UrQA-Client-Android#22]
버그리포팅을 정상적으로 수행하는지 테스트를 하기 위해 RuntimeException을 일부러 생성 throw하였는 데 아무런 반응이 없고 웹사이트에도 집계가 안됩니다.

로그를 확인해 보니 [아래] 와 같은 SocketTimeoutException이 발생하는 군요. 어떻게 해야 할까요?

05-19 13:55:50.710  23555-23594 W/System.err﹕ org.apache.http.conn.ConnectTimeoutException: Connect to /210.122.7.23:80 timed out

05-19 13:55:50.711  23555-23594 W/System.err﹕ at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)

05-19 13:55:50.711  23555-23594 W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)

05-19 13:55:50.711  23555-23594 W/System.err﹕ at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)

05-19 13:55:50.711  23555-23594 W/System.err﹕ at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)

05-19 13:55:50.711  23555-23594 W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)

05-19 13:55:50.711  23555-23594 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)

05-19 13:55:50.712  23555-23594 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)

05-19 13:55:50.712  23555-23594 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)

05-19 13:55:50.712  23555-23594 W/System.err﹕ at com.urqa.common.SendErrorProcess.run(SendErrorProcess.java:44)

05-19 13:55:51.653  23555-23585 W/System.err﹕ java.net.SocketTimeoutException

05-19 13:55:51.654  23555-23585 W/System.err﹕ at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)

05-19 13:55:51.655  23555-23585 W/System.err﹕ at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)

05-19 13:55:51.655  23555-23585 W/System.err﹕ at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)

05-19 13:55:51.655  23555-23585 W/System.err﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)

05-19 13:55:51.655  23555-23585 W/System.err﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:191)

05-19 13:55:51.655  23555-23585 W/System.err﹕ at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:82)

05-19 13:55:51.655  23555-23585 W/System.err﹕ at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)

05-19 13:55:51.656  23555-23585 W/System.err﹕ at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)

05-19 13:55:51.656  23555-23585 W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)

05-19 13:55:51.656  23555-23585 W/System.err﹕ at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)

05-19 13:55:51.656  23555-23585 W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)

05-19 13:55:51.656  23555-23585 W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)

05-19 13:55:51.657  23555-23585 W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)

05-19 13:55:51.657  23555-23585 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)

05-19 13:55:51.657  23555-23585 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)

05-19 13:55:51.657  23555-23585 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)

05-19 13:55:51.657  23555-23585 W/System.err﹕ at com.urqa.common.Network.PostSend(Network.java:85)

05-19 13:55:51.657  23555-23585 W/System.err﹕ at com.urqa.common.Network.run(Network.java:50)

**Comment by EastComplete** [comment]
안녕하세요. 손영수입니다. 안드로이드 클라이언트 버전이 무엇인가요? 문의 드립니다. :)

**Comment by EffectiveLife** [comment]
안녕하세요 손영수님. 단말정보 및 클라이언트 버전 [아래]와 같이 공유드립니다.

하드웨어 :  LG-G3 (LG-F400K)
OS : Android 5.0, 커널버전 3.4.0

**Comment by EffectiveLife** [comment]
안녕하세요. 5.0 이하 단말에서 동일한 테스트 수행하니 이번엔 리포트는 되는데 [아래]와 같은 메세지가 출력되네요.

05-19 16:08:36.781  22606-22620 W/System.err﹕ org.apache.http.conn.ConnectTimeoutException: Connect to /210.122.7.23:80 timed out
05-19 16:08:36.781  22606-22620 W/System.err﹕ at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:188)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:167)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:125)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.executeOriginal(DefaultRequestDirector.java:1227)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:677)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:570)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:491)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:469)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at com.urqa.common.Network.PostSend(Network.java:85)
05-19 16:08:36.781  22606-22620 W/System.err﹕ at com.urqa.common.Network.run(Network.java:50)

**Comment by EastComplete** [comment]
@EffectiveLife  아 안녕하세요 :) 미스 커뮤니케이션이 사용하시고 게신 저희 라이브러리 안드로이드 클라이언트 버전을 문의 드렸습니다. 0.98 쓰시나요?

**Comment by EffectiveLife** [comment]
@EastComplete 0.97버전(UrQA-Client_0.97) 사용 중입니다. :-)

**Comment by EffectiveLife** [comment]
@EastComplete 동일하게 다시 5.0 버전 단말기 (G3)에서 테스트해봤는데 리포팅 카운트가 올라가지 않는 걸로 봐서는 URQA서버로 메세지 발송 자체가 해당 버전에서는 실패하는 것 같습니다.

**Comment by EastComplete** [comment]
정말 죄송한데요 @EffectiveLife 0.95버전으로 한번 테스트 해주실수 있을가요?

**Comment by EffectiveLife** [comment]
05-19 16:18:09.085    8565-8593 W/System.err﹕ java.net.SocketTimeoutException
05-19 16:18:09.085    8565-8593 W/System.err﹕ at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
05-19 16:18:09.085    8565-8593 W/System.err﹕ at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
05-19 16:18:09.085    8565-8593 W/System.err﹕ at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
05-19 16:18:09.085    8565-8593 W/System.err﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:191)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:82)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at com.urqa.common.Network.PostSend(Network.java:85)
05-19 16:18:09.086    8565-8593 W/System.err﹕ at com.urqa.common.Network.run(Network.java:50)

**Comment by EastComplete** [comment]
해당 메세지는 실시간으로 전송되지 않구요. 중간에  redis에서 pub/sub으로 머금었다가 일괄 write됩니다. 바로 실시간으로는 올라오지 않습니다. :)  조금만 지켜봐주세요 한 10분 내외일겁니다 :)

**Comment by EffectiveLife** [comment]
@EastComplete 일단 0.95버전은 콘솔에서 200이라는 메세지 뜨는것 확인했구요. 상기 동일한 메세지는 출력됩니다. 10분 정도 기다려보겠습니다.

**Comment by EastComplete** [comment]
저희때문에 테스트를 해주셔서 감사합니다! @EffectiveLife 님. 
facebook  메세지로 project key 여쭈어보고 저희도 같이 볼게요.

**Comment by EffectiveLife** [comment]
@EastComplete 좋은 서비스를 오픈해주셨는데 제가 감사하지요. 저도 지금 다른거 요청좀 처리하고 다시 보겠습니다. 감사합니다.

**Comment by EffectiveLife** [comment]
@EastComplete  한시간 이상 경과했으나 0.95, 0.97, 0.98 버전 모두 Android OS 5.0 (LG-F400K) 단말에서 발송한 에러 리포트는 갱신되지 않네요. Request 자체가 Failed 된 것 같습니다. 혹시 5.0 이상의 다른 단말에서 테스트 가능하면 테스팅 후 결과 공유하겠습니다.

**Comment by EastComplete** [comment]
@EffectiveLife 안녕하세요 지금 서버 앞단 다시 점검하고 있습니다.
haporxy라는 proxy 에 무언가 문제가 있는지.
또.. node.js만 올려서 어느쪽에 병목이 있느닞 전체적으로 점검하고 있습니다. 

바쁘신 시간 내주셔서 감사합니다.  그리고 저희에게 귀한 시간 내주셔서.. 죄송하네요. .

**Comment by EffectiveLife** [comment]
@EastComplete 안녕하세요 좋은 아침입니다.

오전에 문제가 발생한 단말에서 URQA 0.98버전으로 테스트를 해보았는데 역시 에러 내용이 서버에 전달되지는 않는 것 같습니다. 다만 어제와는 조금 다른 로그가 보여서 이 또한 하단에 첨부하겠습니다. 
GitHub에 클래스 파일로 업로드가 되어 있어 프로젝트 모듈로 참조해서 볼 수는 없는 것 같네요. 현재 상황에서 로그를 첨부해 드리는게 최선의 방법인것 같습니다.

05-20 09:41:45.077  19590-19607/? W/System.err﹕ org.apache.http.NoHttpResponseException: The target server failed to respond
05-20 09:41:45.078  19590-19607/? W/System.err﹕ at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:85)
05-20 09:41:45.078  19590-19607/? W/System.err﹕ at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
05-20 09:41:45.078  19590-19607/? W/System.err﹕ at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
05-20 09:41:45.078  19590-19607/? W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
05-20 09:41:45.086  19590-19607/? W/System.err﹕ at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
05-20 09:41:45.086  19590-19607/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
05-20 09:41:45.087  19590-19607/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
05-20 09:41:45.087  19590-19607/? W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
05-20 09:41:45.087  19590-19607/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
05-20 09:41:45.087  19590-19607/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
05-20 09:41:45.087  19590-19607/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
05-20 09:41:45.087  19590-19607/? W/System.err﹕ at com.urqa.common.Network.PostSend(Network.java:85)
05-20 09:41:45.088  19590-19607/? W/System.err﹕ at com.urqa.common.Network.run(Network.java:50)


05-20 09:46:20.656  22655-22673/? W/System.err﹕ java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:191)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:82)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
05-20 09:46:20.675  22655-22673/? W/System.err﹕ at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at com.urqa.common.Network.sendPostMethod(Network.java:102)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at com.urqa.common.Network.run(Network.java:51)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at libcore.io.Posix.recvfromBytes(Native Method)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at libcore.io.Posix.recvfrom(Posix.java:161)
05-20 09:46:20.676  22655-22673/? W/System.err﹕ at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
05-20 09:46:20.677  22655-22673/? W/System.err﹕ at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
05-20 09:46:20.677  22655-22673/? W/System.err﹕ ... 18 more


05-20 09:46:20.754  22655-22676/? E/URQA Client﹕ UrQA Response Code : 200
05-20 09:46:20.790  22655-22655/? W/System.err﹕ java.lang.StringIndexOutOfBoundsException: length=122; regionStart=65; regionLength=-66
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at java.lang.String.startEndAndLength(String.java:504)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at java.lang.String.substring(String.java:1333)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at com.urqa.common.Encryptor.getJsonToken(Encryptor.java:119)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at com.urqa.common.Encryptor.access$0(Encryptor.java:114)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at com.urqa.common.Encryptor$1.handleMessage(Encryptor.java:77)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5274)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:372)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
05-20 09:46:20.791  22655-22655/? W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
05-20 09:46:25.198  22655-22667/? W/CursorWrapperInner﹕ Cursor finalized without prior close()

**Comment by EffectiveLife** [comment]
위 로그들을 쭉 보니 Apache HttpClient를 내부적으로 사용하고 있는 것 같은데 어떤 이유라도 있으신지요? 짧은 지식으로 볼 때 해당 Lib는 상기 에러들에 대한 관련이 있어 보이고 장기적으로도 변경하시는 게 좋지 않나 싶은데(http://helloworld.naver.com/helloworld/textyle/377316), 제가 모르는 어떤 선정 사유가 있나 궁금해서요. 아 물론 언급하기 곤란한 문제라면 답변 안해주셔도 됩니다. : )

**Comment by EastComplete** [comment]
안녕하세요. 초장기 다른 라이브러리들을 넣었습니다. 그때 발생한 문제는 저희가 사용한 외부라이브러리와 업체에서 동일한 라이브러리를 사용하시면 버전 충돌 문제로 복잡한 문제가 생겼습니다. 그래서 현재 기본을 사용하고 있구요.. 지금 발생한 문제의 원인은 다른 곳에 있습니다. :)

**Comment by EffectiveLife** [comment]
음 문제 해결하셨다는 메세지 확인 후 0.97버전(http://urqa.io/static/tutorial/UrQA-Client_0.97.jar) 으로 테스트 해보았는데요. 이런 말씀 드리기 모하지만... 잘 되는 것 같지 않습니다. 저만 발생하는 문제일까요? ;; 마찬가지로 제가 본 로그 첨부합니다.

05-20 15:52:10.858  17032-17085/? W/System.err﹕ java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:103)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:191)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:82)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
05-20 15:52:10.860  17032-17085/? W/System.err﹕ at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
05-20 15:52:10.861  17032-17085/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
05-20 15:52:10.861  17032-17085/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
05-20 15:52:10.861  17032-17085/? W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
05-20 15:52:10.861  17032-17085/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
05-20 15:52:10.861  17032-17085/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
05-20 15:52:10.862  17032-17085/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
05-20 15:52:10.862  17032-17085/? W/System.err﹕ at com.urqa.common.SendErrorProcess.run(SendErrorProcess.java:44)
05-20 15:52:10.862  17032-17085/? W/System.err﹕ Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
05-20 15:52:10.862  17032-17085/? W/System.err﹕ at libcore.io.Posix.recvfromBytes(Native Method)
05-20 15:52:10.862  17032-17085/? W/System.err﹕ at libcore.io.Posix.recvfrom(Posix.java:161)
05-20 15:52:10.862  17032-17085/? W/System.err﹕ at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
05-20 15:52:10.863  17032-17085/? W/System.err﹕ at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
05-20 15:52:10.863  17032-17085/? W/System.err﹕ ... 17 more
05-20 15:52:10.893  17032-17051/? W/System.err﹕ org.apache.http.NoHttpResponseException: The target server failed to respond
05-20 15:52:10.893  17032-17051/? W/System.err﹕ at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:85)
05-20 15:52:10.893  17032-17051/? W/System.err﹕ at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
05-20 15:52:10.893  17032-17051/? W/System.err﹕ at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
05-20 15:52:10.893  17032-17051/? W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
05-20 15:52:10.893  17032-17051/? W/System.err﹕ at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
05-20 15:52:10.893  17032-17051/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
05-20 15:52:10.893  17032-17051/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
05-20 15:52:10.893  17032-17051/? W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
05-20 15:52:10.894  17032-17051/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
05-20 15:52:10.894  17032-17051/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
05-20 15:52:10.894  17032-17051/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
05-20 15:52:10.894  17032-17051/? W/System.err﹕ at com.urqa.common.Network.PostSend(Network.java:85)
05-20 15:52:10.894  17032-17051/? W/System.err﹕ at com.urqa.common.Network.run(Network.java:50)



05-20 16:02:15.763    8751-8818/? W/System.err﹕ org.apache.http.NoHttpResponseException: The target server failed to respond
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:85)
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:174)
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:180)
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:235)
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:259)
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:279)
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:428)
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
05-20 16:02:15.764    8751-8818/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
05-20 16:02:15.765    8751-8818/? W/System.err﹕ at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
05-20 16:02:15.765    8751-8818/? W/System.err﹕ at com.urqa.common.SendErrorProcess.run(SendErrorProcess.java:44)

**Comment by EastComplete** [comment]
안녕하세요. 저희 서버의 안정성을 위해서 timeout을 5초로 걸어놓았ㅅ브니다. 5초안에 전송이 되면 전달이 되구요. 그렇지 않으면 전송이 되지 않습니다.  
지금 node.js 앞에 data validation을 체크하는 httpproxy를 하나 더두어서 이전보다는 데이터 수집이 잘됩니다. 확인을 해보심녀 될듯합니다.

**Comment by EastComplete** [comment]
데이터 포멧에 맞지않는 여러 데이터들이 들어오면서 node.js 서버에서 행이 걸린 문제였습니다..  일단 하루만에 할수 있는 조치는 취했구요. 낮에 시간애서 더 다듬어 보도록 하겠습니다.

**Comment by EastComplete** [comment]
클라우드 회사 서버의 라우팅 문제로, 데이터가 수집 안된 상황이었습니다..
